### ISSUE TITLE
Use --max-connect and --max-time

### ISSUE THREAD

**Issue by dolevf** [woodruffw/twa#16]
Looping over a list where one of the domains is not responsive/other will result in the script hanging due to curl not using a timeout.

You can use --max-connect or --max-time with a timeout value. maybe pass the value as a flag?

**Comment by woodruffw** [comment]
Good idea! It looks like `--max-time` is probably what we want, since `--connect-timeout` will only handle the connection phase (and we test that with `nc` anyways).

>  maybe pass the value as a flag?

For the time being, I'd like to keep `twa`'s command-line surface pretty minimal. I'm thinking an that an environment variable (`TWA_TIMEOUT`?) + a sensible default (5 seconds?) would be a good fit here.

I'll probably wrap this whole business in a `fetch` function or something similar, so that we apply all of our `curl` options consistently.

**Comment by woodruffw** [comment]
Addressed in b644dddeddd0ed74d874116848dfc9a968cb7396.
